export const filesName = [
  'allItems.json',
  'blogCollectionTemplate.json',
  'blogTemplate.json',
  'buyerActivateAccount.json',
  'buyerLogin.json',
  'buyerRegister.json',
  'buyerResetPassword.json',
  'cart.json',
  'categoryTemplate.json',
  'home.json',
  'itemCollectionList.json',
  'itemCollectionTemplate.json',
  'itemTemplate.json',
  'pageTemplate.json',
  'searchItem.json',
  'announce.json',
  'buyerPay.json',
  'footer.json',
  'globalSetting.json',
  'header.json',
];

export const defaultFilesName = [
  'allItems.json',
  'blogCollectionTemplate.json',
  'blogTemplate.json',
  'buyerActivateAccount.json',
  'buyerLogin.json',
  'buyerRegister.json',
  'buyerResetPassword.json',
  'cart.json',
  'categoryTemplate.json',
  'home.json',
  'itemCollectionList.json',
  'itemCollectionTemplate.json',
  'itemTemplate.json',
  'pageTemplate.json',
  'searchItem.json',
];

export const groupNameList = [
  { value: '轮播图', label: '轮播图' },
  { value: '商品', label: '商品' },
  { value: '图文', label: '图文' },
  { value: '视频', label: '视频' },
  { value: '文本', label: '文本' },
  { value: '博客', label: '博客' },
  { value: '其他', label: '其他' },
];
